// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  var className = "\n    rounded-md\n    py-4\n    px-8\n    text-5xl\n    w-64\n  " + props.className;
  return JsxRuntime.jsx("button", {
              children: props.text,
              className: className,
              onClick: props.onClick
            });
}

var make = Button;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
