// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./Button.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Controls(props) {
  var startButton = JsxRuntime.jsx(Button.make, {
        className: "\n        bg-sky-400\n        text-white\n        hover:bg-sky-500\n        hover:shadow-md\n      ",
        text: "Start",
        onClick: props.onStartClick
      });
  var activeButtons = JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx(Button.make, {
                className: "\n          bg-yellow-400\n          text-white\n          hover:bg-yellow-500\n          hover:shadow-md\n        ",
                text: "Reset",
                onClick: props.onResetClick
              }),
          JsxRuntime.jsx(Button.make, {
                className: "\n          bg-gray-400\n          text-white\n          hover:bg-gray-500\n          hover:shadow-md\n        ",
                text: props.isPaused ? "Resume" : "Pause",
                onClick: props.onPauseResumeClick
              })
        ],
        className: "flex justify-between gap-2"
      });
  return JsxRuntime.jsx("div", {
              children: props.isActive ? activeButtons : startButton,
              className: "mx-auto"
            });
}

var make = Controls;

export {
  make ,
}
/* Button Not a pure module */
