// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Digit(props) {
  var className = "\n    inline-block\n    text-9xl\n  " + props.className;
  return JsxRuntime.jsx("span", {
              children: props.digit,
              className: className
            });
}

var make = Digit;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
