// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Formatter from "../utils/Formatter.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Timer(props) {
  var time = props.time;
  var d1 = Formatter.formatD1(time);
  var d2 = Formatter.formatD2(time);
  var d3 = Formatter.formatD3(time);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("span", {
                      children: d1
                    }),
                JsxRuntime.jsx("span", {
                      children: d2
                    }),
                JsxRuntime.jsx("span", {
                      children: d3
                    })
              ]
            });
}

var make = Timer;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
