// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

function format(time, divideBy, modBy) {
  var floored = Math.floor(time / divideBy) | 0;
  var modded = Caml_int32.mod_(floored, modBy);
  var str = "0" + modded.toString();
  return str.slice(-2);
}

function formatD1(__x) {
  return format(__x, 60000.0, 60);
}

function formatD2(__x) {
  return format(__x, 1000.0, 60);
}

function formatD3(__x) {
  return format(__x, 10.0, 100);
}

export {
  formatD1 ,
  formatD2 ,
  formatD3 ,
}
/* No side effect */
